config/routes.rb
Rails.application.routes.draw do
  resources :pets, only: [:index, :new, :create, :show, :edit, :update]
  resources :owners, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord

  has_many :pets

  # validates :name, presence: true

end

app/models/pet.rb
class Pet < ApplicationRecord

belongs_to :owner

# validates :name, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new
    #if @owner.valid?
      @owner.save
      redirect_to @owner
    # else render :new
    # end
  end

  def show
    @owner = Owner.find(params[:id])
  end
  #I should be able to see all of an owner's pets from his/her show page
  #I should be able to navigate to a pet's show page from it's owner's show page

  private

  # def owner_params
  #   params.require(:owner).permit(:name)
  # end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

# before_action :fetch_pet, only: [:show, :edit, :update]

  def index
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new
    #if @pet.valid?
      @pet.save
      redirect_to @pet     #pet_path(@pet)
    #else render :new
    #end
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    #if @pet.valid?
      @pet.update(pet_params)
      redirect_to @pet
    # else render :edit
    # end
  end

private

def pet_params
  params.require(:pet).permit(:name)
end

# def fetch_pet
#   @pet = Pet.find(params[:id])
# end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ownr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/new.html.erb
<h1> Owner Form </h1>

<%= form_for @owner do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/owners/show.html.erb
<h3> Name </h3>
<%= @owner.name %>

app/views/pets/edit.html.erb
<h2> Edit Pet </h2>

<%= form_for @pet do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/pets/index.html.erb
<h1> Pets </h1>

<% @pets.each do |pet| %>
<%= link_to @pet.name, @pet %>     
<% end %>

app/views/pets/new.html.erb
<h1> Pet Form </h1>

<%= form_for @pet do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :type %>
<%= f.text_field :type %>
<%= f.label :owner_id %>
<%= f.number_field :owner_id %>
<%= f.submit %>
<% end %>

app/views/pets/show.html.erb
<%= @pet.name %><br>
<%= @pet.type %><br>
<%= @pet.owner_id %><br>

<%= link_to "All Pets", pets_path %>